/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForSaleRouteImport } from './routes/for-sale'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutoSlugRouteImport } from './routes/auto.$slug'

const ForSaleRoute = ForSaleRouteImport.update({
  id: '/for-sale',
  path: '/for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoSlugRoute = AutoSlugRouteImport.update({
  id: '/auto/$slug',
  path: '/auto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/for-sale': typeof ForSaleRoute
  '/auto/$slug': typeof AutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/for-sale': typeof ForSaleRoute
  '/auto/$slug': typeof AutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/for-sale': typeof ForSaleRoute
  '/auto/$slug': typeof AutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contatti' | '/for-sale' | '/auto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contatti' | '/for-sale' | '/auto/$slug'
  id: '__root__' | '/' | '/contatti' | '/for-sale' | '/auto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContattiRoute: typeof ContattiRoute
  ForSaleRoute: typeof ForSaleRoute
  AutoSlugRoute: typeof AutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/for-sale': {
      id: '/for-sale'
      path: '/for-sale'
      fullPath: '/for-sale'
      preLoaderRoute: typeof ForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto/$slug': {
      id: '/auto/$slug'
      path: '/auto/$slug'
      fullPath: '/auto/$slug'
      preLoaderRoute: typeof AutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContattiRoute: ContattiRoute,
  ForSaleRoute: ForSaleRoute,
  AutoSlugRoute: AutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
